name: Fetch Autobahn Traffic Delays

on:
  schedule:
    - cron: '*/15 * * * *'   # every 15 minutes
  workflow_dispatch:

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup R  
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.3'
                
      - name: Confirm R version
        run: |
          R --version
          Rscript -e 'cat(.libPaths(), sep = "\n")'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev

      - name: Install R packages
        run: |
          # ensure folder for installation exists
          mkdir -p "${R_LIBS_USER}"
          
          # install into the folder 
          Rscript -e 'install.packages(
            c("httr","jsonlite","dplyr","purrr","tibble","stringr"),
            lib = Sys.getenv("R_LIBS_USER"),
            repos="https://cloud.r-project.org"
          )'

      - name: Run fetch_delays.R
        run: Rscript fetch_delays.R

      - name: Commit and push data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.csv
          if ! git diff --cached --quiet; then
            git commit -m "chore: update autobahn delays data"
            git push
          else
            echo "No changes to commit."
          fi
