name: Fetch Autobahn Traffic Delays

# Run on a 15-minute cron schedule:
on:
  schedule:
    - cron:  '*/15 * * * *'
  workflow_dispatch:  # allow manual trigger

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      # 1) check out the repo
      - uses: actions/checkout@v3

      # 2) set up R (uses r-lib’s Action)
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'   # or whatever version you need

      # 3) install your R dependencies
      - name: Install R packages
        run: |
          install.packages(c("httr","jsonlite","dplyr","purrr","tibble","stringr"), repos = "https://cloud.r-project.org")

      # 4) run your script
      - name: Run fetch_delays.R
        run: Rscript fetch_delays.R

      # 5) Commit and push any new files under data/
      - name: Commit and push data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.csv
          # only commit if there’s something new
          if ! git diff --cached --quiet; then
            git commit -m "chore: update autobahn delays data"
            git push
          else
            echo "No changes to commit."
          fi
