name: Fetch Autobahn Traffic Delays

on:
  schedule:
    - cron: '*/15 * * * *'   # every 15 minutes
  workflow_dispatch:

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'

      - name: Install R packages
        run: >
          Rscript -e 'install.packages(
             c("httr","jsonlite","dplyr","purrr","tibble","stringr"),
             repos="https://cloud.r-project.org"
          )'

      - name: Run fetch_delays.R
        run: Rscript fetch_delays.R

      - name: Commit and push data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.csv
          if ! git diff --cached --quiet; then
            git commit -m "chore: update autobahn delays data"
            git push
          else
            echo "No changes to commit."
          fi
